# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2reg():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2reg(self):
    self.driver.get("http://localhost/car-wash-website-template/reg.php")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.ID, "signup-username").click()
    self.driver.find_element(By.ID, "signup-username").send_keys("tom")
    self.driver.find_element(By.CSS_SELECTOR, ".register-container").click()
    self.driver.find_element(By.ID, "signup-email").click()
    self.driver.find_element(By.ID, "signup-email").send_keys("tom123@gmail.com")
    self.driver.find_element(By.ID, "signup-password").click()
    self.driver.find_element(By.ID, "signup-password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(4)").click()
    self.driver.find_element(By.ID, "confirm-password").click()
    self.driver.find_element(By.ID, "confirm-password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".signup-btn").click()
  
