# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSalesprice():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_salesprice(self):
    self.driver.get("http://localhost/car-wash-website-template/index.php")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.CSS_SELECTOR, ".owl-stage").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(8) > span").click()
    self.driver.find_element(By.NAME, "price").click()
    self.driver.find_element(By.NAME, "price").click()
    self.driver.find_element(By.NAME, "price").send_keys("500.00")
    self.driver.find_element(By.CSS_SELECTOR, ".category-section:nth-child(2) tr:nth-child(1) > td:nth-child(4) .price-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".category-section:nth-child(2) tr:nth-child(3) > td:nth-child(2) .price-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".category-section:nth-child(2) tr:nth-child(3) > td:nth-child(2) .price-input").send_keys("900.00")
  
