# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStaff():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_staff(self):
    self.driver.get("http://localhost/car-wash-website-template/index.php")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "emailInput").send_keys("admin@example.com")
    self.driver.find_element(By.ID, "passwordInput").send_keys("Admin@123")
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-section:nth-child(2) span").click()
    self.driver.find_element(By.ID, "email").send_keys("admin@example.com")
    self.driver.find_element(By.ID, "password").send_keys("Admin@123")
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("tom")
    self.driver.find_element(By.CSS_SELECTOR, ".add-staff-form").click()
    element = self.driver.find_element(By.LINK_TEXT, "Staff Management")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.LINK_TEXT, "Staff Management")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.LINK_TEXT, "Staff Management")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    self.driver.find_element(By.ID, "email").send_keys("tom22@gmail.com")
    self.driver.find_element(By.ID, "phone").click()
    self.driver.find_element(By.ID, "phone").send_keys("9447089632")
    self.driver.find_element(By.ID, "role").click()
    dropdown = self.driver.find_element(By.ID, "role")
    dropdown.find_element(By.XPATH, "//option[. = 'Car Washer']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    self.driver.find_element(By.ID, "password").send_keys("tom12345")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-btn").click()
    self.driver.find_element(By.ID, "email").send_keys("admin@example.com")
    self.driver.find_element(By.ID, "password").send_keys("Admin@123")
  
